### ISSUE TITLE
Investigate `ago` pod restarts 

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1185]
`ago` restarted 4 times since the deployment on 20th of Jan. This is most-likely caused by resource constraints as the node is deliberately deployed with minimal resources.

*  Investigate why by checking logs and metrics on CPU/memory consumption.
* Increase resources conservatively as needed.

**Comment by ischasny** [comment]
The pod has been `OOMKilled`

```
❯ kubectl get pod -n storetheindex --output=yaml ago-indexer-d75dc778-g84cr
...
    lastState:
      terminated:
        containerID: docker://68e4d737406096aed3d3a7e4f2d0681c41e246f8ad3885322a5116f8120906d8
        exitCode: 137
        finishedAt: "2023-01-23T08:25:50Z"
        reason: OOMKilled
        startedAt: "2023-01-21T02:04:05Z"
    name: indexer
    ready: true
    restartCount: 5
    started: true
 ...
```

Will increase RAM in a follow up PR.
